language: node_js
node_js:
  - 14

git:
  depth: 3
script:
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  target_branch: gh-pages
  on:
    branch: master

 