language: 
cache:
 directories:
  - ~/.npm
node_js:
- '14.17.6'
git:
  depth: 3
script:
- yarn build
branches:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  local-dir: dist/
  target_branch: gh-pages 
  on:
   branch: master

 